---
- name: Get key 
  apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9 state=present
  when: ansible_os_family == 'Debian'
  
- name: Get repository
  apt_repository: repo='ppa:marutter/rdev'
  when: ansible_os_family == 'Debian'
  
- name: Update
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'
  
- name: Upgrade
  apt: upgrade=dist
  when: ansible_os_family == 'Debian'
  
- name: Install R on Debian
  apt: name=r-base state=latest update_cache=yes
  when: ansible_os_family == 'Debian'
  
- name: Install R on REL 
  yum: name=name=r-base state=latest update_cache=yes
  when: ansible_os_family == 'RedHat'
  
- include: rcommander.yml
  when: "{{ install_rcommander }}"
  
- include: rstudio.yml
  when: "{{ install_rstudio }}"


