---
- name: Download R-Studio for Debian
  apt: deb=http://download1.rstudio.org/rstudio-0.99.903-amd64.deb dpkg_options='force-depends'
  when: ansible_os_family == 'Debian'    

- name: Install R-Studio on RedHat
  action:  "shell yum install https://download1.rstudio.org/rstudio-0.99.903-x86_64.rpm  -y" 
  when: ansible_os_family == 'RedHat' 
  

